name: Publish dataset zips

on:
  push:
    branches: [ "main" ]
    paths:
      - "datasets/image/**/*"
      - ".github/workflows/publish-datasets.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PUSH_TOKEN }}

      - name: Zip Files
        run: |
          ln -s datasets data
          mv data/image/forest-sat/01crop/*jpg data/image/forest-sat/
          rm -rf data/image/forest-sat/00orig data/image/forest-sat/01crop
          tar -czf forest-sat.tar.gz data/image/forest-sat

      - name: Tag Release
        id: tag
        run: |
          GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-8)
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          TAG_NAME=${{ github.ref_name }}-$(git log --format=%h -1)
          echo "TAG_NAME=$TAG_NAME" >> $GITHUB_OUTPUT
          git tag $TAG_NAME
          git push origin $TAG_NAME

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            *.tar.gz
          tag_name: ${{ steps.tag.outputs.TAG_NAME }}
          token: ${{ secrets.PUSH_TOKEN }}
