name: Publish Docker Images

on:
  push:
    branches: [ "main" ]
    paths:
      - ".github/workflows/publish-ghcr.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 2
          token: ${{ secrets.PACKAGE_PUSH_TOKEN }}

      - name: Create Dockerfiles
        run: |
          echo -e "FROM mcr.microsoft.com/devcontainers/python:3.10\nRUN apt-get update\nRUN apt-get install -y llvm llvm-dev\nRUN pip3 install ipykernel ipywidgets matplotlib pandas scikit-learn gradio_client opencv-python-headless opencv-contrib-python-headless librosa\n" > ./ds.Dockerfile
          echo -e "FROM mcr.microsoft.com/devcontainers/python:3.10\nRUN apt-get update\nRUN apt-get install -y llvm llvm-dev\nRUN pip3 install ipykernel ipywidgets matplotlib pandas scikit-learn gradio_client opencv-python-headless opencv-contrib-python-headless librosa\nRUN pip3 install torch torchvision tqdm --index-url https://download.pytorch.org/whl/cpu\nRUN pip3 install transformers\n" > ./nn.Dockerfile

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PACKAGE_PUSH_TOKEN }}

      - name: Build and push DS Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./ds.Dockerfile
          push: true
          tags: ghcr.io/psam-5005-2026s-a/5005-utils:ds
